/**
 * 
 */
package com.amazonaws.healthcare.model;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

import com.amazonaws.healthcare.util.SensorType;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;

import lombok.Data;

/**
 * @author yashvant
 *
 */
@Data
@DynamoDBTable(tableName = "device")
public class Device {
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	String id;
	@NotNull
	@DynamoDBTypeConvertedEnum
	@DynamoDBRangeKey(attributeName = "type")
	SensorType type;
	@DynamoDBAttribute(attributeName = "patient_id")
	String patientId;
	@NotEmpty
	@DynamoDBAttribute(attributeName = "device_name")
	String deviceName;
	@NotEmpty
	@DynamoDBAttribute(attributeName = "ip_address")
	String ipAddress;
	@NotNull
	@DynamoDBAttribute(attributeName = "port")
	Integer port;
	@NotEmpty
	@DynamoDBAttribute(attributeName = "protocal")
	String protocal;

}
